# Font
font_family      MesloLGS Nerd Font Mono
font_size        17.0

# Window
background_opacity 0.7
initial_window_cols 160
initial_window_rows 50
hide_window_decorations yes
tab_bar_style hidden

# Colors
foreground #CBE0F0
background #011423
cursor #47FF9C
cursor_text_color #011423
selection_background #033259
selection_foreground #CBE0F0

# ANSI colors
color0  #214969
color1  #E52E2E
color2  #44FFB1
color3  #FFE073
color4  #0FC5ED
color5  #a277ff
color6  #24EAF7
color7  #24EAF7

# Brights
color8  #214969
color9  #E52E2E
color10 #44FFB1
color11 #FFE073
color12 #A277FF
color13 #a277ff
color14 #24EAF7
color15 #24EAF7

# Tilde key fix (Alt+n -> ~)
map alt+n send_text all ~
